#! /usr/bin/env python3

from argparse import ArgumentParser
from collections import OrderedDict
from datetime import datetime, timedelta
from fitparse import FitFile
import pandas as pd
import pytz


def fit2csv(fit_path, locale, detect_gaps):
    """Based on Github package https://github.com/dtcooper/python-fitparse"""

    def utc2local(naive_utc, local):
        return pytz.utc.localize(naive_utc).astimezone(local)

    # Load FIT data
    fitfile = FitFile(fit_path)
    records = [r for r in fitfile.get_messages('record', as_dict=True)]
    fields_stoi = OrderedDict({f['name']: i for i, f in enumerate(records[0]['fields'])})
    if 'timestamp' not in fields_stoi:
        raise RuntimeError(f'Records do not contain timestamps')

    # Convert FIT timestamps from UTC to user's locale
    # Use the starting date to name the CSV export
    tz = pytz.timezone(locale)
    for r in records:
        local_ts = r['fields'][fields_stoi['timestamp']]['value']
        r['fields'][fields_stoi['timestamp']]['value'] = utc2local(local_ts, tz)
    start_local = records[0]['fields'][fields_stoi['timestamp']]['value']
    csv_path = f'{datetime.strftime(start_local, "%Y%m%d")}.csv'

    # Parse into CSV
    # Extract all field values for each record and add an activity time counter
    rows = [[timedelta(seconds=s)] + [r['fields'][idx]['value'] for idx in fields_stoi.values()]
            for s, r in enumerate(records)]
    df = pd.DataFrame(rows, columns=['activity'] + list(fields_stoi.keys()))
    df.to_csv(csv_path, index=False)

    # Check for timeseries gaps if requested
    if detect_gaps:
        deltas = df.diff().timestamp[1:]
        gaps = deltas[deltas > timedelta(seconds=1)]
        if len(gaps) > 0:
            print(f'Found {len(gaps)} gaps in heart rate data')
        for i, g in gaps.iteritems():
            gap_start = df.timestamp[i - 1]
            print(f'\t* {datetime.strftime(gap_start, "%I:%M:%S %p")}: {str(g.to_pytimedelta())}'.expandtabs(4))


if __name__ == '__main__':

    parser = ArgumentParser(description='Extract heart rate data from Garmin fit file')
    parser.add_argument('fit_path', type=str, help='path to .fit data')
    parser.add_argument('-g', '--gaps', action='store_true', help='print any timeseries gaps > 1s')
    parser.add_argument('-l', '--locale', type=str, default='US/Mountain', help='location of activity')
    args = parser.parse_args()

    fit2csv(args.fit_path, args.locale, args.gaps)
